language: node_js
node_js: lts/*
before_install: npm i -g grunt
install: yarn
script: grunt
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  target-branch: master
  on:
    branch: develop
branches:
  except:
  - master